name: mobile
version: 0.1.0+1
description: FocusFlow offline-first habit and application tracker.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.5.0
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0
  uuid: ^4.4.2
  connectivity_plus: ^6.0.5
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - .env
